# Generated by Django 5.2.9 on 2025-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomieradar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('HOSTEL_ONLY', 'Hostel Only'), ('ROOMMATE', 'Roommate')], default='HOSTEL_ONLY', max_length=20),
        ),
    ]
