# Generated by Django 5.2.9 on 2025-12-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomieradar_app', '0002_room_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='booked_at',
        ),
    ]
