# Generated by Django 5.2.9 on 2025-12-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomieradar_app', '0003_rename_booked_on_booking_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='roomieradar_app.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'Non-AC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupied_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', '2 Sharing'), ('3', '3 Sharing'), ('4', '4 Sharing')], max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_beds',
            field=models.PositiveIntegerField(),
        ),
    ]
