# Generated by Django 5.2.9 on 2025-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomieradar_app', '0004_alter_booking_room_alter_room_ac_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupied_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_beds',
            field=models.IntegerField(editable=False),
        ),
    ]
