# Generated by Django 5.2.9 on 2025-12-20 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('room_sharing', models.IntegerField(blank=True, null=True)),
                ('ac_preference', models.CharField(blank=True, max_length=10, null=True)),
                ('bedtime', models.CharField(blank=True, max_length=20, null=True)),
                ('cleanliness', models.CharField(blank=True, max_length=20, null=True)),
                ('noise_tolerance', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('smoking_alcohol', models.CharField(blank=True, max_length=20, null=True)),
                ('food_type', models.CharField(blank=True, max_length=20, null=True)),
                ('personality', models.CharField(blank=True, max_length=20, null=True)),
                ('pet_tolerance', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('sharing_belongings', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('group_study', models.CharField(blank=True, max_length=10, null=True)),
                ('call_frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('study_importance', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('email_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
