# Generated by Django 5.2.9 on 2025-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='smoking_alcohol',
        ),
        migrations.AddField(
            model_name='preferences',
            name='smoking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
